### ISSUE TITLE
Crashes after a few minutes

### ISSUE THREAD

**Issue by sirmodok** [avinson/rom24-quickmud#4]
After a few minutes of playing, the game crashes and the container restarts (if you use --policy=restart)
The error is 

```
Thu Dec 17 18:06:33 2015 :: [*****] BUG: Save_char_obj: fopen
../player/Modok: No such file or directory
```

So it attempted to save the character but failed.

The reason being that /opt/rom/ is missing the "player" directory
Once I created that directory everything seemed to save and work fine

Maybe consider adding a 

```
RUN mkdir -p /opt/rom/player
```

in the Docker file.

**Comment by avinson** [comment]
done. thanks for catching this.
