### ISSUE TITLE
Player Files not showing up

### ISSUE THREAD

**Issue by Chuchutta** [avinson/rom24-quickmud#7]
I ran the `docker run -d -p 4000:4000 avinson/rom` command, mud ran. Cannot find any player files. Running on ubuntu 17.10.

**Comment by Chuchutta** [comment]
I figured it out. I had to get into the docker container using `docker exec -i -t <container> bash`.

**Comment by grphx7** [comment]
Thank you for this!

**Comment by avinson** [comment]
@Chuchutta I added some additional docs and a docker-compose.yml file to make this easier.
